import { VerticalBox } from "std-widgets.slint";

component TireRectangle inherits Rectangle{
    in property <color> bg-color;
    in property <color> text-color;
    in property <float> tire_temp;
    Rectangle {
        border-width: 1px;
        border-color: white;
        background: bg-color;
        Text {
            font-size: 20px;
            text: "\{tire_temp}°F";
            color: text-color;
        }
    }
}

export component Dashboard inherits Window {
    min-width: 800px;
    min-height: 500px;

    in property <float> rpm;
    in property <float> speed;
    in property <string> best_lap;
    in property <string> current_lap;
    in property <string> delta;
    in property <float> temp_left_f;
    in property <float> temp_right_f;
    in property <float> temp_left_r;
    in property <float> temp_right_r;
    in property <int> lap_number;
    in property <int> gear;
    in property <int> position;
    in property <percent> accel;
    in property <percent> brake;
    in property <bool> new_best;

    property <color> bg-color: #000000;
    property <color> text-color: #ffffff;
    property <color> rpm_off: #C0C0C1;
    property <color> rpm1: #00FF00;
    property <color> rpm2: #ffaa00;
    property <color> rpm3: #ff0000;
    property <int> led_height: 25;
    property <int> led_width: 25;
    property <int> led_border: 15;
    property <color> delta_color: text-color;

    // Define a model for RPM lights
    in property <[bool]> rpm_lights: [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
    ];

    GridLayout {
        min-height: 500px;
        min-width: 800px;

        /// Top row with RPM lights
        Rectangle {
            col: 0;
            row: 0;
            colspan: 3;
            height: 10%;
            background: bg_color;
            HorizontalLayout {
                padding: 15px;
                spacing: 28px;
                alignment: center;

                for led in rpm_lights.length: Rectangle {
                    width: led_width * 1px;
                    height: led_height * 1px;
                    background: rpm_lights[led] ? rpm1 : rpm_lights[led] && led > 4 ? rpm2 : rpm_lights[led] && led > 9 ? rpm3 : rpm_off;
                    border-radius: led_border * 1px;
                }
            }
        }

        // Left side
        VerticalLayout {
            width: 25%;
            col: 0;
            row: 1;

            Rectangle {
                border-width: 1px;
                border-color: white;
                background: bg-color;

                VerticalBox {
                    Text {
                        font-size: 40px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        text: "\{root.speed}";
                        color: text-color;
                    }

                    Text {
                        font-size: 15px;
                        horizontal-alignment: center;
                        text: "mph";
                        color: text-color;
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: white;
                background: bg-color;

                VerticalBox {
                    Text {
                        font-size: 40px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        text: "\{root.rpm}";
                        color: text-color;
                    }

                    Text {
                        font-size: 15px;
                        horizontal-alignment: center;
                        text: "rpm";
                        color: text-color;
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: white;
                height: 15%;
                background: bg-color;
                Text {
                    font-size: 30px;
                    text: "P\{root.position}";
                    color: text-color;
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: white;
                height: 15%;
                background: bg-color;
                Text {
                    font-size: 30px;
                    text: "L\{root.lap_number}";
                    color: text-color;
                }
            }
        }

        // Center
        VerticalLayout {
            width: 50%;
            col: 1;
            row: 1;

            GridLayout {

                // Left thin rectangle
                Rectangle {
                    background: @linear-gradient(0deg, red root.brake, black 0%);
                    row: 0;
                    col: 0;
                    width: 5%;
                    height: 100%;
                    border-width: 1px;
                    border-color: white;
                }

                // Gear rectangle
                Rectangle {
                    row: 0;
                    col: 1;
                    height: 70%;
                    background: bg-color;
                    border-width: 1px;
                    border-color: white;
                    VerticalBox {
                        Text {
                            font-size: 100px;
                            text: "\{root.gear}";
                            horizontal-alignment: center;
                            vertical-alignment: center;
                            color: text-color;
                        }

                        Text {
                            font-size: 20px;
                            text: "Gear";
                            horizontal-alignment: center;
                            color: text-color;
                        }
                    }
                }

                // Right thin rectangle
                Rectangle {
                    background: @linear-gradient(0deg, green root.accel, black 0%);
                    row: 0;
                    col: 2;
                    width: 5%;
                    height: 100%;
                    border-width: 1px;
                    border-color: white;
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: white;
                background: bg-color;
                height: 10%;
                Text {
                    font-size: 15px;
                    text: "Current: \{root.current_lap}";
                    color: text-color;
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: white;
                height: 10%;
                background: bg-color;

                HorizontalLayout {
                    Text {
                        font-size: 15px;
                        text: "Delta: ";
                        color: text-color;
                        horizontal-alignment: right;
                        vertical-alignment: center;
                    }

                    if root.delta == "": Text {
                        font-size: 15px;
                        text: "N/A";
                        color: text-color;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                    }
                    if root.new_best: Text {
                        font-size: 15px;
                        text: "Delta: \{root.delta}";
                        color: #00FF00;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                    }
                    if (!root.new_best && root.delta != ""): Text {
                        font-size: 15px;
                        text: "+\{root.delta}";
                        color: #FF0000;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: white;
                height: 10%;
                background: bg-color;
                Text {
                    font-size: 15px;
                    text: "Best: \{root.best_lap}";
                    color: text-color;
                }
            }
        }

        // Right side
        VerticalLayout {
            width: 25%;
            col: 2;
            row: 1;
            // Tire temp
            Rectangle {
                VerticalLayout {
                    HorizontalLayout {
                        height: 50%;
                        width: 50%;
                        TireRectangle {
                            bg-color: bg-color;
                            text-color: text-color;
                            tire_temp: root.temp_left_f;
                        }
                        TireRectangle {
                            bg-color: bg-color;
                            text-color: text-color;
                            tire_temp: root.temp_right_f;
                        }
                    }

                    HorizontalLayout {
                        height: 50%;
                        width: 50%;
                        TireRectangle {
                            bg-color: bg-color;
                            text-color: text-color;
                            tire_temp: root.temp_left_r;
                        }
                        TireRectangle {
                            bg-color: bg-color;
                            text-color: text-color;
                            tire_temp: root.temp_right_r;
                        }
                    }
                }
            }
        }
    }
}
