import { VerticalBox } from "std-widgets.slint";

export component Dashboard inherits Window {
    min-width: 800px;
    min-height: 500px;
    callback update_values();
    in property <float> rpm: 0.0;
    in property <float> speed;
    in property <float> best_lap;
    in property <float> current_lap;
    in property <float> race_time;
    in property <int> gear;
    GridLayout {
        Row {
            Rectangle {
            height: 100px;
            colspan: 3;
                Text {
                    text: "\{root.rpm}";
                }
                background: red;
            }
        }


        Row {
            Rectangle {
                colspan: 1;
                height: 300px;
                Text {
                    text: "Best lap Time";
                }
                background: green;
            }

            Rectangle {
                colspan: 1;
                height: 300px;
                in property <int> gear;
                Text {
                    font-size: 20px;
                    text: gear;
                }
                background: blue;
            }

            Rectangle {
                colspan: 1;
                height: 300px;
                VerticalBox {
                    alignment: center;
                    Text {
                        text: "Current lap Time";
                    }
                    Text {
                        text: "last lap Time";
                    }
                }
                background: purple;
            }
        }


        Row {
            Rectangle {
            height: 100px;
                colspan: 3;
                Text {
                    text: "Speed";
                }
                background: red;
            }
        }
    }
}